site_name: My Wiki
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.tabs.link
    - content.code.copy

nav:
  - Home: 
      - Home: index.md
  - Sideloading: 
      - Overview: side/index.md
      - Sideloading with PC: side/pc-free.md
      - Buying a Dev Account: side/dev-account.md
      - Paid Certificates: side/enterprise.md
      - Leaked Certificates: side/leaked.md
      - Jailbreaking Your Device: side/jailbreak.md
  - FAQ: faq.md

  - Guides:
      - Guides Overview: guides/index.md
      - Getting Started: guides/getting-started.md
      - Advanced: guides/advanced.md
  - Tools:
      - Tools Overview: tools/index.md
      - Android: tools/android.md
      - iOS: tools/ios.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg